### ISSUE TITLE
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by huang-fuxian** [vlomonaco/crlmaze#2]
Hello, after sucessfully installed all the required packages guided by the README, when I state run "./scripts/run_setup.sh", the following error occurs, do you know what's wrong with it? Thanks.

**Comment by huang-fuxian** [comment]
![微信截图_20210826105017](https://user-images.githubusercontent.com/89465566/130895471-bbb05e6a-168f-418e-bed1-39bf5755d531.png)
![微信截图_20210826105047](https://user-images.githubusercontent.com/89465566/130895482-0be97d81-a05d-45bb-b75f-f392fa3e2d36.png)

**Comment by PhiCtl** [comment]
Hi @huang-fuxian ! I'm currently facing the same issue. How did you solve it ?
